---
name: Golangci-lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go: ["1.17", "1.18"]
        os: [ubuntu-latest, windows-latest]
    name: Run golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Golang lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: true
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
